name = "product-journey-master"
compatibility_date = "2024-01-01"

[build]
command = "bun install && bun run build"

[site]
bucket = "./dist"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false

[env.development]
workers_dev = true