name = "product-journey-master"
main = "src/_worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "bun run build"
watch_dir = "src"

[env.production]
workers_dev = false

[env.development]
workers_dev = true