name = "product-journey-master"
main = "src/_worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[build]
command = "bun install && bun run build"
watch_dir = "src"

[env.production]
workers_dev = false

[env.development]
workers_dev = true

# Add environment variables
[vars]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

# Pages specific configuration
[build.upload]
format = "service-worker"

[pages_build_output_dir]
value = "dist"